# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\EXEamp1e\PycharmProjects\BD\ConfirmDel.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfirmDel(object):
    def setupUi(self, ConfirmDel):
        ConfirmDel.setObjectName("ConfirmDel")
        ConfirmDel.resize(393, 295)
        self.gridLayout = QtWidgets.QGridLayout(ConfirmDel)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(ConfirmDel)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(ConfirmDel)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(ConfirmDel)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(ConfirmDel)
        QtCore.QMetaObject.connectSlotsByName(ConfirmDel)

    def retranslateUi(self, ConfirmDel):
        _translate = QtCore.QCoreApplication.translate
        ConfirmDel.setWindowTitle(_translate("ConfirmDel", "Dialog"))
        self.pushButton.setText(_translate("ConfirmDel", "Да"))
        self.pushButton_2.setText(_translate("ConfirmDel", "Нет"))
        self.label.setText(_translate("ConfirmDel", "Вы действительно хотите удалить аккаунт?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConfirmDel = QtWidgets.QDialog()
    ui = Ui_ConfirmDel()
    ui.setupUi(ConfirmDel)
    ConfirmDel.show()
    sys.exit(app.exec_())
