# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\EXEamp1e\PycharmProjects\BD\RegSuccess.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegSuccess(object):
    def setupUi(self, RegSuccess):
        RegSuccess.setObjectName("RegSuccess")
        RegSuccess.resize(400, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(RegSuccess)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(RegSuccess)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(RegSuccess)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 0, 1, 1)

        self.retranslateUi(RegSuccess)
        QtCore.QMetaObject.connectSlotsByName(RegSuccess)

    def retranslateUi(self, RegSuccess):
        _translate = QtCore.QCoreApplication.translate
        RegSuccess.setWindowTitle(_translate("RegSuccess", "Dialog"))
        self.label.setText(_translate("RegSuccess", "Вы успешно зарегестрировались. Войдите в аккаунт"))
        self.pushButton.setText(_translate("RegSuccess", "Ок"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegSuccess = QtWidgets.QDialog()
    ui = Ui_RegSuccess()
    ui.setupUi(RegSuccess)
    RegSuccess.show()
    sys.exit(app.exec_())
